### ISSUE TITLE
Discuss Falco Images and how they are built

### ISSUE THREAD

**Issue by mfdii** [falcosecurity/office-hours#10]
**What type of proposal is this?**
/kind issue

**Details about the discussion**

I'd like to discuss the plan for slim and large images as detailed in the open Falco issue: https://github.com/falcosecurity/falco/issues/532

**Comment by fntlnz** [comment]
Discussed: https://github.com/falcosecurity/office-hours/blob/master/meeting-notes/2019-Jun-13.md

/close
