### ISSUE TITLE
Rule parsing errors

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/office-hours#24]
**What type of proposal is this?**

/kind pr

**Details about the discussion**

Let's discuss the PR from @mstemm about Rule parsing errors, he wants to overview us that PR so that we can merge it fast!

https://github.com/falcosecurity/falco/pull/708

**Comment by leodido** [comment]
This PR is now merged. Furthermore in the last Office Hours (notes PR is #25) we approached the topic.
