### ISSUE TITLE
Add to your Calendar (GMail) does not work

### ISSUE THREAD

**Issue by markyjackson-taulia** [falcosecurity/office-hours#31]
What type of proposal is this?

/kind issue

`Add to your Calendar (GMail)` in readme does not work

**Comment by leodido** [comment]
Also the zoom URL have to be updated probably.

**Comment by kris-nova** [comment]
to what?

**Comment by leodido** [comment]
To the zoom URL in the calendar event Kris :)

**Comment by kris-nova** [comment]
Change the zoom link to what link :wink:

**Comment by markyjackson-taulia** [comment]
I think the zoom link is fine and needs no changing in the new calendar entry once it is created

**Comment by kris-nova** [comment]
If we don't need to change either of these, can we close the issue please:

- Zoom link in the office hours README
- Zoom link in the falco README

**Comment by markyjackson-taulia** [comment]
This issue is for the calendar being incorrect not the zoom 🤔

**Comment by markyjackson-taulia** [comment]
but now I see that calendar entry has been removed so this issue is no longer valid.
Nothing to see here
