### ISSUE TITLE
Implement HackMD

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/office-hours#36]
**What type of proposal is this?**

/kind issue

**Details about the discussion**

I am wondering if we want to implement the HackMD service for office hours? It saves us the time of going from Google Docs to Markdown, and I think Markdown is our goal here. 

https://hackmd.io

**Comment by leodido** [comment]
Done in the 2019 Sept 4th office hours. Notes [here](meeting-notes/2019-Sep-04.md). We agree on using it, it's awesome!
