### ISSUE TITLE
Demo of the test grids' kernel builder

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/office-hours#39]
**What type of proposal is this?**

/kind debugging-hours

**Details about the discussion**

Wanted to show everyone a possible solution we can use to build kernels for the upcoming test grid.

The purpose is to gather feedback and make it a bit better and more stable afterwards.

**Comment by leodido** [comment]
Done in the 2019 Sept 4th office hours. Notes [here](meeting-notes/2019-Sep-04.md).

Video will be published soon.
