### ISSUE TITLE
Improved Falco Ouputs

### ISSUE THREAD

**Issue by Issif** [falcosecurity/office-hours#5]
Hi,

I propose to talk about future of falco's outputs. Until now, outputs are quite simple and formatting is limited. We've already an issue of falco's repo side about with more details :

https://github.com/falcosecurity/falco/issues/528

/kind issue

**Comment by fntlnz** [comment]
Thanks @Issif ! I'll move this to in discussion for the meeting on 06/06/19, if you can't make it we'll push it back to proposals.

**Comment by fntlnz** [comment]
Discussed: https://github.com/falcosecurity/office-hours/blob/master/meeting-notes/2019-Jun-06.md
