### ISSUE TITLE
GitHub and contribution automation

### ISSUE THREAD

**Issue by leodido** [falcosecurity/office-hours#6]
**What type of proposal is this?**

> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind issue
> /kind pr

/kind issue

**Details about the discussion**

I would like to discuss how automation could improve the contributing workflow to the Falco open source organization and to its repositories.

About this matter I already proposed a solution into the [issue 621](https://github.com/falcosecurity/falco/issues/621), where you can read more details about it.

In short, it presents [prow](https://github.com/kubernetes/test-infra/tree/master/prow), a tool which provides CI features as well as a **set of plugins/bots/tools** aimed at improving developers productivity and open source management by automating workflows as much as possible.

By the way, for completeness, you could see an initial automation in this repo itself (implemented by the [test-infra](https://github.com/falcosecurity/test-infra) one).

**Comment by fntlnz** [comment]
Discussed: https://github.com/falcosecurity/office-hours/blob/master/meeting-notes/2019-Jun-06.md
